name: ship

on:
  release:
    types:
      - published

jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.8
        bundler-cache: true
    - name: Deploy to RubyGems
      run: bundle exec rake release
