name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PUNK_ENV: test
      COVERALLS_REPO_TOKEN: "${{secrets.COVERALLS_REPO_TOKEN}}"
      IPSTACK_ACCESS_KEY: "${{secrets.IPSTACK_ACCESS_KEY}}"
      USERSTACK_API_KEY: "${{secrets.USERSTACK_API_KEY}}"
      DATABASE_URL: "postgres://postgres:postgres@localhost/punk_test"

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      memcached:
        image: memcached
        ports:
          - 11211:11211
        options: --health-cmd "timeout 5 bash -c 'cat < /dev/null > /dev/udp/127.0.0.1/11211'" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.8
        bundler-cache: true
    - name: Lint files
      run: bundle exec rubocop
    - name: Run specs
      run: |
        bundle exec ruby ./bin/punk db create
        bundle exec ruby ./bin/punk db migrate
        bundle exec rspec
