name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PUNK_ENV: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.8
        bundler-cache: true
    - name: Lint files
      run: bundle exec rubocop
    - name: Run specs
      run: bundle exec rspec
